<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="MAIN" Id="{4243ffa1-1c68-4f3e-be95-ae41ec879a6f}">
    <Declaration><![CDATA[PROGRAM MAIN

VAR

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[GEMMA();
WATER_TANKS();
AIS();
SAFETY();
Q1_MOTOR();
Q2_MOTOR();

]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>