<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="GEMMA" Id="{caba80c3-9027-4275-b033-341dad53175a}">
    <Declaration><![CDATA[PROGRAM GEMMA
VAR
	STEP_A6: INT := 0;
	DELAY_EJECTION_CARRIERS: TON;
	DELAY_STARTING_AIR: TON;
	EJECT_CARRIERS: BOOL;
	F2_END: BOOL;
	STEP: STRING(20);
	START_AIR: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"A6 "</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">10L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">11L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">12L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">13L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">14L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"A6_Action"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">15L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">16L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">17L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">177L</v>
                          <v n="IdParent">9L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">178L</v>
                          <v n="IdParent">9L</v>
                        </o>
                      </l2>
                      <v n="Id">9L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList" cet="SFCTransition">
                                <o>
                                  <v n="VariableName">"Branch0__A6__to__A1"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.INIT_OK"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">26L</v>
                                      <v n="IdParent">25L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">27L</v>
                                      <v n="IdParent">25L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">181L</v>
                                      <v n="IdParent">25L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">182L</v>
                                      <v n="IdParent">25L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">25L</v>
                                  <v n="IdParent">22L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">23L</v>
                                <v n="IdParent">22L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">24L</v>
                                <v n="IdParent">22L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">180L</v>
                                <v n="IdParent">22L</v>
                              </o>
                            </l2>
                            <v n="Id">22L</v>
                            <v n="IdParent">18L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__A6__to__D1"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.SAFETY_OK=0"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">32L</v>
                                      <v n="IdParent">31L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">33L</v>
                                      <v n="IdParent">31L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">184L</v>
                                      <v n="IdParent">31L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">185L</v>
                                      <v n="IdParent">31L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">31L</v>
                                  <v n="IdParent">28L</v>
                                </o>
                                <o t="SFCJump">
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"D1"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">35L</v>
                                      <v n="IdParent">34L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">36L</v>
                                      <v n="IdParent">34L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">186L</v>
                                      <v n="IdParent">34L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">34L</v>
                                  <v n="IdParent">28L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">29L</v>
                                <v n="IdParent">28L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">30L</v>
                                <v n="IdParent">28L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">183L</v>
                                <v n="IdParent">28L</v>
                              </o>
                            </l2>
                            <v n="Id">28L</v>
                            <v n="IdParent">18L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">19L</v>
                          <v n="IdParent">18L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">20L</v>
                          <v n="IdParent">18L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">21L</v>
                          <v n="IdParent">18L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">179L</v>
                          <v n="IdParent">18L</v>
                        </o>
                      </l2>
                      <v n="Id">18L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCStep">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"A1"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">38L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">39L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">40L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">41L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">42L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"A1_Action"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">43L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">44L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">45L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">187L</v>
                          <v n="IdParent">37L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">188L</v>
                          <v n="IdParent">37L</v>
                        </o>
                      </l2>
                      <v n="Id">37L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList" cet="SFCTransition">
                                <o>
                                  <v n="VariableName">"Branch0__A1__to__F1"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.AUTO"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">54L</v>
                                      <v n="IdParent">53L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">55L</v>
                                      <v n="IdParent">53L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">191L</v>
                                      <v n="IdParent">53L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">192L</v>
                                      <v n="IdParent">53L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">53L</v>
                                  <v n="IdParent">50L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">51L</v>
                                <v n="IdParent">50L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">52L</v>
                                <v n="IdParent">50L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">190L</v>
                                <v n="IdParent">50L</v>
                              </o>
                            </l2>
                            <v n="Id">50L</v>
                            <v n="IdParent">46L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__A1__to__A4"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.MANUAL"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">60L</v>
                                      <v n="IdParent">59L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">61L</v>
                                      <v n="IdParent">59L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">194L</v>
                                      <v n="IdParent">59L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">195L</v>
                                      <v n="IdParent">59L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">59L</v>
                                  <v n="IdParent">56L</v>
                                </o>
                                <o t="SFCStep">
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"A4"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">63L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">64L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">65L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">66L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">67L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"A4_Action"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">68L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">69L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">70L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">196L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">197L</v>
                                      <v n="IdParent">62L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">62L</v>
                                  <v n="IdParent">56L</v>
                                </o>
                                <o t="SFCBranch">
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" cet="SFCSegment">
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList" cet="SFCTransition">
                                            <o>
                                              <v n="VariableName">"Branch1_0__A4__to__A6"</v>
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"FLAGS.MANUAL=0"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">79L</v>
                                                  <v n="IdParent">78L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">80L</v>
                                                  <v n="IdParent">78L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">200L</v>
                                                  <v n="IdParent">78L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">201L</v>
                                                  <v n="IdParent">78L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">78L</v>
                                              <v n="IdParent">75L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">76L</v>
                                            <v n="IdParent">75L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">77L</v>
                                            <v n="IdParent">75L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">199L</v>
                                            <v n="IdParent">75L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">75L</v>
                                        <v n="IdParent">71L</v>
                                      </o>
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList">
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Branch1_1__A4__to__D1"</v>
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"FLAGS.SAFETY_OK=0"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">85L</v>
                                                  <v n="IdParent">84L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">86L</v>
                                                  <v n="IdParent">84L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">203L</v>
                                                  <v n="IdParent">84L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">204L</v>
                                                  <v n="IdParent">84L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">84L</v>
                                              <v n="IdParent">81L</v>
                                            </o>
                                            <o t="SFCJump">
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"D1"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">88L</v>
                                                  <v n="IdParent">87L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">89L</v>
                                                  <v n="IdParent">87L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">205L</v>
                                                  <v n="IdParent">87L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">87L</v>
                                              <v n="IdParent">81L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">82L</v>
                                            <v n="IdParent">81L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">83L</v>
                                            <v n="IdParent">81L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">202L</v>
                                            <v n="IdParent">81L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">81L</v>
                                        <v n="IdParent">71L</v>
                                      </o>
                                    </l2>
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">72L</v>
                                      <v n="IdParent">71L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">73L</v>
                                      <v n="IdParent">71L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">74L</v>
                                      <v n="IdParent">71L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">198L</v>
                                      <v n="IdParent">71L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">71L</v>
                                  <v n="IdParent">56L</v>
                                </o>
                                <o t="SFCJump">
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"A6"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">91L</v>
                                      <v n="IdParent">90L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">92L</v>
                                      <v n="IdParent">90L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">206L</v>
                                      <v n="IdParent">90L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">90L</v>
                                  <v n="IdParent">56L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">57L</v>
                                <v n="IdParent">56L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">58L</v>
                                <v n="IdParent">56L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">193L</v>
                                <v n="IdParent">56L</v>
                              </o>
                            </l2>
                            <v n="Id">56L</v>
                            <v n="IdParent">46L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch2__A1__to__D1"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.SAFETY_OK=0"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">97L</v>
                                      <v n="IdParent">96L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">98L</v>
                                      <v n="IdParent">96L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">208L</v>
                                      <v n="IdParent">96L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">209L</v>
                                      <v n="IdParent">96L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">96L</v>
                                  <v n="IdParent">93L</v>
                                </o>
                                <o t="SFCJump">
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"D1"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">100L</v>
                                      <v n="IdParent">99L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">101L</v>
                                      <v n="IdParent">99L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">210L</v>
                                      <v n="IdParent">99L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">99L</v>
                                  <v n="IdParent">93L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">94L</v>
                                <v n="IdParent">93L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">95L</v>
                                <v n="IdParent">93L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">207L</v>
                                <v n="IdParent">93L</v>
                              </o>
                            </l2>
                            <v n="Id">93L</v>
                            <v n="IdParent">46L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">47L</v>
                          <v n="IdParent">46L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">48L</v>
                          <v n="IdParent">46L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">49L</v>
                          <v n="IdParent">46L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">189L</v>
                          <v n="IdParent">46L</v>
                        </o>
                      </l2>
                      <v n="Id">46L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCStep">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"F1"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">103L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">104L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">105L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">106L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">107L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"F1_Action"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">108L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">109L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">110L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">211L</v>
                          <v n="IdParent">102L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">212L</v>
                          <v n="IdParent">102L</v>
                        </o>
                      </l2>
                      <v n="Id">102L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList" cet="SFCTransition">
                                <o>
                                  <v n="VariableName">"Branch0__F1__to__D1"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.SAFETY_OK=0"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">119L</v>
                                      <v n="IdParent">118L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">120L</v>
                                      <v n="IdParent">118L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">215L</v>
                                      <v n="IdParent">118L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">216L</v>
                                      <v n="IdParent">118L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">118L</v>
                                  <v n="IdParent">115L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">116L</v>
                                <v n="IdParent">115L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">117L</v>
                                <v n="IdParent">115L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">214L</v>
                                <v n="IdParent">115L</v>
                              </o>
                            </l2>
                            <v n="Id">115L</v>
                            <v n="IdParent">111L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__F1__to__F2"</v>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"FLAGS.AUTO=0"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">125L</v>
                                      <v n="IdParent">124L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">126L</v>
                                      <v n="IdParent">124L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">218L</v>
                                      <v n="IdParent">124L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">219L</v>
                                      <v n="IdParent">124L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">124L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o t="SFCStep">
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"F2"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">128L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">129L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">130L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">131L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">132L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"F2_Action"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">133L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">134L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">135L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">220L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">221L</v>
                                      <v n="IdParent">127L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">127L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o t="SFCBranch">
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" cet="SFCSegment">
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList" cet="SFCTransition">
                                            <o>
                                              <v n="VariableName">"Branch1_0__F2__to__A1"</v>
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"F2_END"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">144L</v>
                                                  <v n="IdParent">143L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">145L</v>
                                                  <v n="IdParent">143L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">224L</v>
                                                  <v n="IdParent">143L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">225L</v>
                                                  <v n="IdParent">143L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">143L</v>
                                              <v n="IdParent">140L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">141L</v>
                                            <v n="IdParent">140L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">142L</v>
                                            <v n="IdParent">140L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">223L</v>
                                            <v n="IdParent">140L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">140L</v>
                                        <v n="IdParent">136L</v>
                                      </o>
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList">
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Branch1_1__F2__to__D1"</v>
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"FLAGS.SAFETY_OK=0"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">150L</v>
                                                  <v n="IdParent">149L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">151L</v>
                                                  <v n="IdParent">149L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">227L</v>
                                                  <v n="IdParent">149L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">228L</v>
                                                  <v n="IdParent">149L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">149L</v>
                                              <v n="IdParent">146L</v>
                                            </o>
                                            <o t="SFCJump">
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"D1"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">153L</v>
                                                  <v n="IdParent">152L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">154L</v>
                                                  <v n="IdParent">152L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">229L</v>
                                                  <v n="IdParent">152L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">152L</v>
                                              <v n="IdParent">146L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">147L</v>
                                            <v n="IdParent">146L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">148L</v>
                                            <v n="IdParent">146L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">226L</v>
                                            <v n="IdParent">146L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">146L</v>
                                        <v n="IdParent">136L</v>
                                      </o>
                                    </l2>
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">137L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">138L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">139L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">222L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">136L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o t="SFCJump">
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"A1"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">156L</v>
                                      <v n="IdParent">155L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">157L</v>
                                      <v n="IdParent">155L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">230L</v>
                                      <v n="IdParent">155L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">155L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">122L</v>
                                <v n="IdParent">121L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">123L</v>
                                <v n="IdParent">121L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">217L</v>
                                <v n="IdParent">121L</v>
                              </o>
                            </l2>
                            <v n="Id">121L</v>
                            <v n="IdParent">111L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">112L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">113L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">114L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">213L</v>
                          <v n="IdParent">111L</v>
                        </o>
                      </l2>
                      <v n="Id">111L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCStep">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"D1"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">159L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">160L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">161L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">162L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">163L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"D1_Action"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">164L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">165L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">166L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">231L</v>
                          <v n="IdParent">158L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">232L</v>
                          <v n="IdParent">158L</v>
                        </o>
                      </l2>
                      <v n="Id">158L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"D1__to__A6"</v>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"FLAGS.SAFETY_OK"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">168L</v>
                          <v n="IdParent">167L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">169L</v>
                          <v n="IdParent">167L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">233L</v>
                          <v n="IdParent">167L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">234L</v>
                          <v n="IdParent">167L</v>
                        </o>
                      </l2>
                      <v n="Id">167L</v>
                      <v n="IdParent">8L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"A6"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">171L</v>
                          <v n="IdParent">170L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">172L</v>
                          <v n="IdParent">170L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">235L</v>
                          <v n="IdParent">170L</v>
                        </o>
                      </l2>
                      <v n="Id">170L</v>
                      <v n="IdParent">8L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">174L</v>
                    <v n="IdParent">8L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">175L</v>
                    <v n="IdParent">8L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">176L</v>
                    <v n="IdParent">8L</v>
                  </o>
                </l2>
                <v n="Id">8L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" />
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="F1_Action" Id="{263b9e56-4c1a-486a-b55d-67d5b96b5874}">
      <Implementation>
        <ST><![CDATA[(*********************************************************
*
* F1
*
************************************************************)

STEP := 'F1';
]]></ST>
      </Implementation>
    </Action>
    <Action Name="A6_Action" Id="{35d361ca-ae43-4b85-80cd-dcdb3546dd6b}">
      <Implementation>
        <ST><![CDATA[(**************************************************************
*
*
* Initialisation
*
*
***************************************************************)
STEP:='A6';



CASE STEP_A6 OF

0: (*Init*)
	STEP_A6:=STEP_A6+1;

1: (*Initialise valves and variables*)

	GEN_1V1 				:=FALSE;	(*Vanne AIR*)
	GEN_CONVOYEUR			:=FALSE;	(*Relais convoyeur*)	
	
	ST1_1V1 	:=FALSE;		(*Vérin palette attente*)
	ST1_1V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST1_1V3 	:=FALSE;		(*Vérin palette stop*)
	ST1_1V4 	:=FALSE;		(*Vérin connexion TOP*)
	ST1_1V5		:=FALSE;		(*Vérin connexion HT*)

	ST2_2V1 	:=FALSE;		(*Vérin palette attente*)
	ST2_2V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST2_2V3 	:=FALSE;		(*Vérin palette stop*)
	ST2_2V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST2_2V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST2_2V6		:=FALSE;		(*Vérin électrique*)
	ST2_2V7		:=FALSE;		(*Vérin by-pass*)
	
	ST2_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST3_3V1 	:=FALSE;		(*Vérin palette attente*)
	ST3_3V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST3_3V3 	:=FALSE;		(*Vérin palette stop*)
	ST3_3V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST3_3V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST3_3V7		:=FALSE;		(*Vérin by-pass*)
	
	ST3_3V10 	:=FALSE;		(*Vanne avant la pompe*)
	ST3_3V11 	:=FALSE;		(*Vanne après la pompe*)
	ST3_3V12 	:=FALSE;		(*Vanne de blocage d'air pour le DELTA*)
	
	ST4_4V1 	:=FALSE;		(*Vérin palette attente*)
	ST4_4V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST4_4V3 	:=FALSE;		(*Vérin palette stop*)
	ST4_4V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST4_4V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST4_4V6		:=FALSE;		(*Vérin électrique*)
	ST4_4V7		:=FALSE;		(*Vérin by-pass*)
	
	ST4_4V10	:=FALSE;		(*Vanne avant la pompe*)
	ST4_4V12	:=FALSE;		(*Vanne après la vanne pilotée*)
	ST4_4V13	:=FALSE;		(*Vanne max flow*)

	ST4_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	ST4_VIDANGE	:=FALSE;		(*Vidange balance*)
	
	ST5_5V1 	:=FALSE;		(*Vérin palette attente*)
	ST5_5V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST5_5V3 	:=FALSE;		(*Vérin palette stop*)
	ST5_5V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST5_5V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST5_5V6		:=FALSE;		(*Vérin électrique*)
	
	ST5_5V10	:=FALSE;		(*Vanne avant la pompe*)
	ST5_5V12	:=FALSE;		(*Vanne après la vanne pilotée*)
	ST5_5V13	:=FALSE;		(*Vanne max flow*)
	
	ST5_5V14	:=FALSE;		(*Vanne vidange vers égouts ou réservoir*)
	ST5_5V15	:=FALSE;			(*Vanne avant la pompe*)
	ST5_5V16	:=FALSE;		(*Vanne provenance eau du réservoir ou du déminéralisateur*)
	
	ST5_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	ST5_VIDANGE	:=FALSE;		(*Vidange balance*)
	
	ST6_6V1 	:=FALSE;		(*Vérin palette attente*)
	ST6_6V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST6_6V3 	:=FALSE;		(*Vérin palette stop*)
	ST6_6V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST6_6V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST6_6V6		:=FALSE;		(*Vérin électrique*)
	ST6_6V7		:=FALSE;		(*Vérin by-pass*)
	
	ST6_6V10	:=FALSE;		(*Vanne avant la pompe*)
	ST6_6V11	:=FALSE;		(*Vanne après la pompe*)
	
	ST6_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST7_7V1 	:=FALSE;		(*Vérin palette attente*)
	ST7_7V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST7_7V3 	:=FALSE;		(*Vérin palette stop*)
	ST7_7V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST7_7V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST7_7V6		:=FALSE;		(*Vérin électrique*)
	ST7_7V7		:=FALSE;		(*Vérin by-pass*)
	
	ST7_7V10	:=FALSE;		(*Vanne avant la pompe*)
	
	ST7_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST8_8V1 	:=FALSE;		(*Vérin palette attente*)
	ST8_8V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST8_8V3 	:=FALSE;		(*Vérin palette stop*)
	ST8_8V4 	:=FALSE;		(*Reserve*)
	
	ST9_9V1 	:=FALSE;		(*Vérin palette attente*)
	ST9_9V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST9_9V3 	:=FALSE;		(*Vérin palette stop*)
	ST9_9V4A 	:=TRUE;			(*Vérin rodless guide*)
	ST9_9V4B 	:=FALSE;		(*Vérin rodless guide*)
	ST9_9V5A 	:=FALSE;		(*Vérin slide table*)
	ST9_9V5B 	:=TRUE;			(*Vérin slide table*)
	ST9_9V6 	:=TRUE;			(*Vérin gripper*)
	ST9_9V7 	:=FALSE;		(*Vérin liberateur electrique*)
	
	ST10_10V1 	:=TRUE;		(*Opérateur 1 - Vérin carrier stop*)
	ST10_10V2 	:=TRUE;		(*Opérateur 2 - Vérin carrier stop*)


	STEP_A6:=STEP_A6+1;

2: (*Start AIR*)

	GEN_1V1 := TRUE;
	START_AIR := TRUE;
	STEP_A6:=STEP_A6+1;

3: (*Wait AIR then start convoyer and wait ejection of carriers*)
	
	IF DELAY_STARTING_AIR.Q THEN
		GEN_CONVOYEUR := TRUE;
		START_AIR := FALSE;
		EJECT_CARRIERS:=TRUE;
		STEP_A6:=STEP_A6+1;
	END_IF;

4: (* Wait carriers ejection *)

	IF DELAY_EJECTION_CARRIERS.Q THEN
		EJECT_CARRIERS:=FALSE;
		STEP_A6:=STEP_A6+1;
	END_IF;
5: (*End of init *)

	FLAGS.INIT_OK:=TRUE;


ELSE
    ;
END_CASE;

(* FBs *)
DELAY_EJECTION_CARRIERS(IN:=EJECT_CARRIERS , PT:=DELAY_EJECT_CARRIERS);
DELAY_STARTING_AIR(IN:=START_AIR , PT:=DELAY_START_AIR);]]></ST>
      </Implementation>
    </Action>
    <Action Name="A1_Action" Id="{9028462a-cc66-4cee-b37e-215f3831f50c}">
      <Implementation>
        <ST><![CDATA[(***************************************************************************
*
* A1
*
****************************************************************************)
STEP := 'A1';
]]></ST>
      </Implementation>
    </Action>
    <Action Name="A4_Action" Id="{9cd56dcb-5c8e-47aa-8797-cf3b6f27d093}">
      <Implementation>
        <ST><![CDATA[STEP:= 'A4';]]></ST>
      </Implementation>
    </Action>
    <Action Name="D1_Action" Id="{b6d83183-e2ee-4c3f-a3f5-f6e80eed41a1}">
      <Implementation>
        <ST><![CDATA[(*****************************************************************
*
* NOT AUS state
*
******************************************************************)

	STEP := 'D1';
	
	STEP_A6:=0;
	F2_END:=FALSE;

	FLAGS.INIT_OK			:=FALSE;
	FLAGS.MOTOR_Q1_INIT_OK	:=FALSE;
	FLAGS.AUTO				:=FALSE;
	FLAGS.MANUAL			:=FALSE;

	GEN_1V1 				:=FALSE;	(*Vanne AIR*)
	GEN_CONVOYEUR			:=FALSE;	(*Relais convoyeur*)	
	
	ST1_1V1 	:=FALSE;		(*Vérin palette attente*)
	ST1_1V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST1_1V3 	:=FALSE;		(*Vérin palette stop*)
	ST1_1V4 	:=FALSE;		(*Vérin connexion TOP*)
	ST1_1V5		:=FALSE;		(*Vérin connexion HT*)

	ST2_2V1 	:=FALSE;		(*Vérin palette attente*)
	ST2_2V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST2_2V3 	:=FALSE;		(*Vérin palette stop*)
	ST2_2V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST2_2V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST2_2V6		:=FALSE;		(*Vérin électrique*)
	ST2_2V7		:=FALSE;		(*Vérin by-pass*)
	
	ST2_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST3_3V1 	:=FALSE;		(*Vérin palette attente*)
	ST3_3V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST3_3V3 	:=FALSE;		(*Vérin palette stop*)
	ST3_3V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST3_3V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST3_3V7		:=FALSE;		(*Vérin by-pass*)
	
	ST3_3V10 	:=FALSE;		(*Vanne avant la pompe*)
	ST3_3V11 	:=FALSE;		(*Vanne après la pompe*)
	ST3_3V12 	:=FALSE;		(*Vanne de blocage d'air pour le DELTA*)
	
	ST4_4V1 	:=FALSE;		(*Vérin palette attente*)
	ST4_4V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST4_4V3 	:=FALSE;		(*Vérin palette stop*)
	ST4_4V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST4_4V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST4_4V6		:=FALSE;		(*Vérin électrique*)
	ST4_4V7		:=FALSE;		(*Vérin by-pass*)
	
	ST4_4V10	:=FALSE;		(*Vanne avant la pompe*)
	ST4_4V12	:=FALSE;		(*Vanne après la vanne pilotée*)
	ST4_4V13	:=FALSE;		(*Vanne max flow*)

	ST4_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	ST4_VIDANGE	:=FALSE;		(*Vidange balance*)
	
	ST5_5V1 	:=FALSE;		(*Vérin palette attente*)
	ST5_5V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST5_5V3 	:=FALSE;		(*Vérin palette stop*)
	ST5_5V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST5_5V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST5_5V6		:=FALSE;		(*Vérin électrique*)
	
	ST5_5V10	:=FALSE;		(*Vanne avant la pompe*)
	ST5_5V12	:=FALSE;		(*Vanne après la vanne pilotée*)
	ST5_5V13	:=FALSE;		(*Vanne max flow*)
	
	ST5_5V14	:=FALSE;		(*Vanne vidange vers égouts ou réservoir*)
	ST5_5V15	:=FALSE;			(*Vanne avant la pompe*)
	ST5_5V16	:=FALSE;		(*Vanne provenance eau du réservoir ou du déminéralisateur*)
	
	ST5_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	ST5_VIDANGE	:=FALSE;		(*Vidange balance*)
	
	ST6_6V1 	:=FALSE;		(*Vérin palette attente*)
	ST6_6V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST6_6V3 	:=FALSE;		(*Vérin palette stop*)
	ST6_6V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST6_6V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST6_6V6		:=FALSE;		(*Vérin électrique*)
	ST6_6V7		:=FALSE;		(*Vérin by-pass*)
	
	ST6_6V10	:=FALSE;		(*Vanne avant la pompe*)
	ST6_6V11	:=FALSE;		(*Vanne après la pompe*)
	
	ST6_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST7_7V1 	:=FALSE;		(*Vérin palette attente*)
	ST7_7V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST7_7V3 	:=FALSE;		(*Vérin palette stop*)
	ST7_7V4 	:=FALSE;		(*Vérin Hydro TOP*)
	ST7_7V5		:=FALSE;		(*Vérin hydro BOTTOM*)
	ST7_7V6		:=FALSE;		(*Vérin électrique*)
	ST7_7V7		:=FALSE;		(*Vérin by-pass*)
	
	ST7_7V10	:=FALSE;		(*Vanne avant la pompe*)
	
	ST7_POWER	:=FALSE;		(*Alimentation électrique pompe*)
	
	ST8_8V1 	:=FALSE;		(*Vérin palette attente*)
	ST8_8V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST8_8V3 	:=FALSE;		(*Vérin palette stop*)
	ST8_8V4 	:=FALSE;		(*Reserve*)
	
	ST9_9V1 	:=FALSE;		(*Vérin palette attente*)
	ST9_9V2 	:=FALSE;		(*Vérin palette bloquage*)
	ST9_9V3 	:=FALSE;		(*Vérin palette stop*)
	ST9_9V4A 	:=TRUE;			(*Vérin rodless guide*)
	ST9_9V4B 	:=FALSE;		(*Vérin rodless guide*)
	ST9_9V5A 	:=FALSE;		(*Vérin slide table*)
	ST9_9V5B 	:=TRUE;			(*Vérin slide table*)
	ST9_9V6 	:=TRUE;			(*Vérin gripper*)
	ST9_9V7 	:=FALSE;		(*Vérin liberateur electrique*)
	
	ST10_10V1 	:=TRUE;		(*Opérateur 1 - Vérin carrier stop*)
	ST10_10V2 	:=TRUE;		(*Opérateur 2 - Vérin carrier stop*)
]]></ST>
      </Implementation>
    </Action>
    <Action Name="F2_Action" Id="{e2a6bd08-06eb-486c-9ebb-86878540e224}">
      <Implementation>
        <ST><![CDATA[STEP := 'F2';]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>